### ISSUE TITLE
err

### ISSUE THREAD

**Issue by Egida** [XYZ-DANO/LAYER7-BYPASS#2]
/root/LAYER7-BYPASS/method.js:3
var refer = process.argv[10].replace(/~/g, '&');
                             ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (/root/LAYER7-BYPASS/method.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by RealAchive1** [comment]
Remove the .replace(/~/g, '&')

**Comment by RealAchive1** [comment]
This is a shit script anyway. Tested it. Not working well xD

**Comment by DANO-AMP** [comment]
> This is a shit script anyway. Tested it. Not working well xD

If you don't have good and updated proxies, it doesn't work well for you.
